[theme]
base = "dark"
primaryColor = "#0066CC"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730" 
textColor = "#fafafa"
font = "sans serif"

[server]
maxUploadSize = 100
enableCORS = false
enableXsrfProtection = true
address = "localhost"
port = 8501

[browser]
gatherUsageStats = false
serverAddress = "localhost"